name: Lint
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
    branches: ['**']
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29