name: Golang workflow

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
    branches: ['**']
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Install
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
      - name: Test
        run: go test -v
      - name: Build
        run: go build .
